spring.application.name=identity-service
server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/smartcampus_identity
spring.datasource.username=root
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
