spring.application.name=smartcampus

# Tells Spring Boot where the database is
spring.datasource.url=jdbc:mysql://localhost:3306/smartcampusdb
spring.datasource.username=root
spring.datasource.password=admin

# Tells Spring Boot to automatically update your tables if you change your Models
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
