spring.application.name=lost-found-service
server.port=8084

spring.datasource.url=jdbc:mysql://localhost:3306/smartcampus_lostfound
spring.datasource.username=root
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

notifications.base-url=
security.gateway-shared-key=smartcampus-internal-gateway-key
