import { Wrench } from 'lucide-react'

export default function CategoryManagementPage({
  beginEditCategory,
  categories,
  categoriesError,
  categoryForm,
  categoryNotice,
  deletingCategoryId,
  distinctDepartmentCount,
  editingCategoryId,
  filteredCategories,
  handleCategorySubmit,
  handleDeleteCategory,
  isCategoriesLoading,
  isSavingCategory,
  resetCategoryForm,
  setCategoryForm,
}) {
  const editingCategory = categories.find((category) => category.id === editingCategoryId) ?? null

  return (
    <section className="mt-6 grid gap-6 2xl:grid-cols-[1.1fr_0.9fr]">
      <div className="rounded-3xl border border-slate-200/80 bg-white p-6 shadow-sm">
        <div className="flex flex-col gap-4 border-b border-slate-200/80 pb-5 lg:flex-row lg:items-start lg:justify-between"><div><h2 className="text-lg font-semibold text-slate-950">Department management</h2><p className="mt-1 text-sm text-slate-500">Manage support departments, routing, service labels, locations, and response targets.</p></div><div className="inline-flex h-12 w-12 items-center justify-center rounded-2xl bg-[#003366] text-white"><Wrench className="h-5 w-5" /></div></div>
        <div className="mt-6 grid gap-4 md:grid-cols-3"><article className="rounded-3xl bg-slate-50 p-5"><p className="text-sm font-semibold text-slate-900">Departments</p><p className="mt-2 text-3xl font-semibold tracking-tight text-slate-950">{categories.length}</p><p className="mt-2 text-sm leading-6 text-slate-500">Total managed departments available for routing.</p></article><article className="rounded-3xl bg-slate-50 p-5"><p className="text-sm font-semibold text-slate-900">Departments</p><p className="mt-2 text-3xl font-semibold tracking-tight text-slate-950">{distinctDepartmentCount}</p><p className="mt-2 text-sm leading-6 text-slate-500">Distinct departments currently mapped to routing.</p></article><article className="rounded-3xl bg-slate-50 p-5"><p className="text-sm font-semibold text-slate-900">Filtered results</p><p className="mt-2 text-3xl font-semibold tracking-tight text-slate-950">{filteredCategories.length}</p><p className="mt-2 text-sm leading-6 text-slate-500">Results matching the current search query.</p></article></div>

        {categoryNotice ? <div className="mt-6 rounded-2xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-800">{categoryNotice}</div> : null}
        {categoriesError ? <div className="mt-6 rounded-2xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-700">{categoriesError}</div> : null}

        <div className="mt-6 overflow-hidden rounded-3xl border border-slate-200/80"><div className="overflow-x-auto"><table className="min-w-full divide-y divide-slate-200 text-left"><thead className="bg-slate-50"><tr><th className="px-5 py-4 text-xs font-semibold uppercase tracking-[0.16em] text-slate-500">Department</th><th className="px-5 py-4 text-xs font-semibold uppercase tracking-[0.16em] text-slate-500">Department</th><th className="px-5 py-4 text-xs font-semibold uppercase tracking-[0.16em] text-slate-500">Location</th><th className="px-5 py-4 text-xs font-semibold uppercase tracking-[0.16em] text-slate-500">Target</th><th className="px-5 py-4 text-xs font-semibold uppercase tracking-[0.16em] text-slate-500">Actions</th></tr></thead><tbody className="divide-y divide-slate-200 bg-white">{isCategoriesLoading ? <tr><td className="px-5 py-6 text-sm text-slate-500" colSpan="5">Loading departments...</td></tr> : filteredCategories.length ? filteredCategories.map((category) => <tr key={category.id} className="align-top"><td className="px-5 py-4"><p className="text-sm font-semibold text-slate-950">{category.name}</p><p className="mt-1 text-xs uppercase tracking-[0.16em] text-slate-500">{category.serviceLabel}</p></td><td className="px-5 py-4 text-sm text-slate-600">{category.department}</td><td className="px-5 py-4 text-sm text-slate-600">{category.defaultLocation}</td><td className="px-5 py-4 text-sm text-slate-600">{category.responseTarget}</td><td className="px-5 py-4"><div className="flex flex-wrap gap-2"><button type="button" onClick={() => beginEditCategory(category)} className="inline-flex h-9 items-center justify-center rounded-2xl border border-slate-200 px-3 text-sm font-medium text-slate-700 transition hover:border-slate-300 hover:text-[#003366]">Edit</button><button type="button" onClick={() => handleDeleteCategory(category)} disabled={deletingCategoryId === category.id} className="inline-flex h-9 items-center justify-center rounded-2xl border border-rose-200 px-3 text-sm font-medium text-rose-700 transition hover:border-rose-300 hover:bg-rose-50 disabled:cursor-not-allowed disabled:opacity-70">{deletingCategoryId === category.id ? 'Deleting...' : 'Delete'}</button></div></td></tr>) : <tr><td className="px-5 py-6 text-sm text-slate-500" colSpan="5">No departments match the current search.</td></tr>}</tbody></table></div></div>
      </div>

      <div className="rounded-3xl border border-slate-200/80 bg-white p-6 shadow-sm">
        <div className="flex items-start justify-between gap-4"><div><h2 className="text-lg font-semibold text-slate-950">{editingCategory ? `Edit ${editingCategory.name}` : 'Create department'}</h2><p className="mt-1 text-sm text-slate-500">Configure how ticket requests are routed and described across the system.</p></div><button type="button" onClick={resetCategoryForm} className="inline-flex h-10 items-center justify-center rounded-2xl border border-slate-200 px-4 text-sm font-medium text-slate-700 transition hover:border-slate-300 hover:text-slate-900">{editingCategory ? 'Cancel edit' : 'Reset'}</button></div>
        <form className="mt-6 space-y-5" onSubmit={handleCategorySubmit}>
          <div className="space-y-2"><label className="text-sm font-medium text-slate-700" htmlFor="category-name">Department name</label><input id="category-name" type="text" required value={categoryForm.name} onChange={(event) => setCategoryForm((currentForm) => ({ ...currentForm, name: event.target.value }))} placeholder="Example: IT Support" className="h-12 w-full rounded-2xl border border-slate-200 bg-slate-50 px-4 text-sm text-slate-900 outline-none transition placeholder:text-slate-400 focus:border-[#003366] focus:bg-white focus:ring-4 focus:ring-[#003366]/10" /></div>
          <div className="space-y-2"><label className="text-sm font-medium text-slate-700" htmlFor="category-department">Department</label><input id="category-department" type="text" required value={categoryForm.department} onChange={(event) => setCategoryForm((currentForm) => ({ ...currentForm, department: event.target.value }))} placeholder="Example: Information Technology Centre" className="h-12 w-full rounded-2xl border border-slate-200 bg-slate-50 px-4 text-sm text-slate-900 outline-none transition placeholder:text-slate-400 focus:border-[#003366] focus:bg-white focus:ring-4 focus:ring-[#003366]/10" /></div>
          <div className="grid gap-5 sm:grid-cols-2"><div className="space-y-2"><label className="text-sm font-medium text-slate-700" htmlFor="department-service-label">Service label</label><input id="department-service-label" type="text" required value={categoryForm.serviceLabel} onChange={(event) => setCategoryForm((currentForm) => ({ ...currentForm, serviceLabel: event.target.value }))} placeholder="Example: Network & systems" className="h-12 w-full rounded-2xl border border-slate-200 bg-slate-50 px-4 text-sm text-slate-900 outline-none transition placeholder:text-slate-400 focus:border-[#003366] focus:bg-white focus:ring-4 focus:ring-[#003366]/10" /></div><div className="space-y-2"><label className="text-sm font-medium text-slate-700" htmlFor="category-response-target">Response target</label><input id="category-response-target" type="text" required value={categoryForm.responseTarget} onChange={(event) => setCategoryForm((currentForm) => ({ ...currentForm, responseTarget: event.target.value }))} placeholder="Example: 4 hours" className="h-12 w-full rounded-2xl border border-slate-200 bg-slate-50 px-4 text-sm text-slate-900 outline-none transition placeholder:text-slate-400 focus:border-[#003366] focus:bg-white focus:ring-4 focus:ring-[#003366]/10" /></div></div>
          <div className="space-y-2"><label className="text-sm font-medium text-slate-700" htmlFor="category-location">Default location</label><input id="category-location" type="text" required value={categoryForm.defaultLocation} onChange={(event) => setCategoryForm((currentForm) => ({ ...currentForm, defaultLocation: event.target.value }))} placeholder="Example: Computer Lab 2" className="h-12 w-full rounded-2xl border border-slate-200 bg-slate-50 px-4 text-sm text-slate-900 outline-none transition placeholder:text-slate-400 focus:border-[#003366] focus:bg-white focus:ring-4 focus:ring-[#003366]/10" /></div>
          <div className="rounded-3xl bg-slate-50 p-4"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-slate-500">Routing summary</p><p className="mt-2 text-sm text-slate-600">The department name appears in ticket forms. Department, service label, location, and response target are used across the public landing page and operations views.</p></div>
          <div className="flex flex-col-reverse gap-3 border-t border-slate-200 pt-5 sm:flex-row sm:justify-end"><button type="button" onClick={resetCategoryForm} className="inline-flex h-11 items-center justify-center rounded-2xl border border-slate-200 px-4 text-sm font-medium text-slate-700 transition hover:border-slate-300 hover:text-slate-900">Clear</button><button type="submit" disabled={isSavingCategory} className="inline-flex h-11 items-center justify-center rounded-2xl bg-[#003366] px-4 text-sm font-semibold text-white shadow-[0_12px_24px_rgba(0,51,102,0.22)] transition hover:bg-[#0a4278] disabled:cursor-not-allowed disabled:opacity-70">{isSavingCategory ? (editingCategoryId ? 'Saving...' : 'Creating...') : (editingCategoryId ? 'Save Changes' : 'Create Department')}</button></div>
        </form>
      </div>
    </section>
  )
}
